-- Suppression des tables s'il elles existent déjà
DROP TABLE IF EXISTS ENCHERE;
DROP TABLE IF EXISTS VENTE;
DROP TABLE IF EXISTS SALLE_VENTE;
DROP TABLE IF EXISTS TYPE_VENTE;
DROP TABLE IF EXISTS CARECTERISTIQUE;
DROP TABLE IF EXISTS PRODUIT;
DROP TABLE IF EXISTS CATEGORIE;
DROP TABLE IF EXISTS UTILISATEUR;

-- Création de la table UTILISATEUR
CREATE TABLE UTILISATEUR (
    EMAIL VARCHAR(50) PRIMARY KEY,
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    ADRESSE VARCHAR(100) NOT NULL
);

-- Création de la table CATEGORIE
CREATE TABLE CATEGORIE (
    NOM VARCHAR (20) PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL
);

-- Création de la table PRODUIT
CREATE TABLE PRODUIT (
    ID_PRODUIT INTEGER PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL,
    PRIX_REVIENT FLOAT NOT NULL,
    STOCK INTEGER NOT NULL,
    CATEGORIE VARCHAR(20) REFERENCES CATEGORIE NOT NULL
);

-- Création de la table CARACTERISTIQUE
CREATE TABLE CARACTERISTIQUE (
    ID_PRODUIT INTEGER PRIMARY KEY REFERENCES PRODUIT,
    NOM VARCHAR(30) NOT NULL,
    VALEUR VARCHAR(50) NOT NULL
);

-- Création de la table TYPE_VENTE
CREATE TABLE TYPE_VENTE (
    TYPE VARCHAR(20) PRIMARY KEY,
    CONSTRAINT TYPECHECK CHECK(TYPE IN ('MONTANTE','DESCENDANTE'))
);

-- Création de la table SALLE_VENTE
CREATE TABLE SALLE_VENTE (
    ID_SALLE INTEGER PRIMARY KEY,
    CATEGORIE VARCHAR(20) REFERENCES CATEGORIE NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    TYPE VARCHAR(20) REFERENCES TYPE_VENTE NOT NULL
);

-- Création de la table VENTE
CREATE TABLE VENTE (
    ID_VENTE INTEGER PRIMARY KEY,
    EMAIL VARCHAR(50) REFERENCES UTILISATEUR NOT NULL,
    ID_PRODUIT INTEGER REFERENCES PRODUIT NOT NULL,
    ID_SALLE INTEGER REFERENCES SALLE_VENTE NOT NULL,
    PRIX_DEPART FLOAT NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DUREE INTEGER NOT NULL,
    REVOCABLE NUMBER(1) NOT NULL,
    ENCHERE_UNIQUE NUMBER(1) NOT NULL,
    CONSTRAINT BOOLEAN CHECK((REVOCABLE IN(0,1)) AND ENCHERE_UNIQUE IN (0,1))
);

-- Création de la table ENCHERE
CREATE TABLE ENCHERE (
    ID_ENCHERE INTEGER PRIMARY KEY,
    EMAIL VARCHAR(50) REFERENCES UTILISATEUR NOT NULL,
    ID_VENTE INTEGER REFERENCES VENTE NOT NULL,
    PRIX_ACHAT FLOAT NOT NULL,
    DATE_ENCHERE DATE
);