    DROP TABLE ENCHERE;
    DROP TABLE VENTE;
    DROP TABLE SALLE_VENTE;
    DROP TABLE TYPE_VENTE;
    DROP TABLE PRODUIT;
    DROP TABLE CARACTERISTQUE;
    DROP TABLE CATEGORIE;
    DROP TABLE UTILISATEUR;

    CREATE TABLE UTILISATEUR (EMAIL VARCHAR(50) PRIMARY KEY, NOM VARCHAR(20) NOT NULL, PRENOM VARCHAR(20) NOT NULL, ADRESSE VARCHAR(100) NOT NULL);
    CREATE TABLE CATEGORIE (NOM VARCHAR (20) PRIMARY KEY, DESCRIPTION VARCHAR(100) NOT NULL);
    CREATE TABLE PRODUIT (ID_PRODUIT INTEGER PRIMARY KEY, NOM VARCHAR(50) NOT NULL, PRIX_REVIENT FLOAT NOT NULL, STOCK INTEGER NOT NULL, CATEGORIE VARCHAR(20) REFERENCES CATEGORIE NOT NULL);
    CREATE TABLE CARECTERISTIQUE (ID_PRODUIT INTEGER PRIMARY KEY REFERENCES PRODUIT, NOM VARCHAR(30) NOT NULL, VALEUR VARCHAR(50) NOT NULL);
    CREATE TABLE TYPE_VENTE(TYPE VARCHAR(20) PRIMARY KEY, CONSTRAINT TYPECHECK CHECK(TYPE IN ('MONTANTE','DESCENDANTE') ));
    CREATE TABLE SALLE_VENTE(ID_SALLE INTEGER PRIMARY KEY, CATEGORIE VARCHAR(20) REFERENCES CATEGORIE NOT NULL, DESCRIPTION VARCHAR(100) NOT NULL, TYPE VARCHAR(20) REFERENCES TYPE_VENTE NOT NULL);
    CREATE TABLE VENTE(ID_VENTE INTEGER PRIMARY KEY, EMAIL VARCHAR(50) REFERENCES UTILISATEUR NOT NULL, ID_PRODUIT INTEGER REFERENCES PRODUIT NOT NULL, ID_SALLE INTEGER REFERENCES SALLE_VENTE NOT NULL, PRIX_DEPART FLOAT NOT NULL, DATE_DEBUT DATE NOT NULL, DUREE INTEGER NOT NULL, REVOCABLE NUMBER(1) NOT NULL, ENCHERE_UNIQUE NUMBER(1) NOT NULL, CONSTRAINT BOOLEAN CHECK((REVOCABLE IN(0,1)) AND ENCHERE_UNIQUE IN (0,1)));
    CREATE TABLE ENCHERE(ID_ENCHERE INTEGER PRIMARY KEY,EMAIL VARCHAR(50) REFERENCES UTILISATEUR NOT NULL,ID_VENTE INTEGER REFERENCES VENTE NOT NULL,PRIX_ACHAT FLOAT NOT NULL, DATE_ENCHERE DATE);
